# Generated by Django 2.2.24 on 2022-09-04 18:40

from django.db import migrations

# pylint: disable=unused-argument


def revert_fill_new_building(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    flat_model.objects.all().update(new_building=None)


def fill_new_building(apps, schema_editors):
    flat_model = apps.get_model('property', 'Flat')
    flats = flat_model.objects.all()
    new_building_limit = 2015
    for flat in flats:
        flat.new_building = flat.construction_year >= new_building_limit
        flat.save(update_fields=['new_building'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building, revert_fill_new_building)
    ]
