# Generated by Django 2.2.24 on 2022-09-04 18:40

from django.db import migrations

# pylint: disable=unused-argument


def revert_fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')  # noqa: N806
    Flat.objects.all().update(new_building=None)


def fill_new_building(apps, schema_editors):
    Flat = apps.get_model('property', 'Flat')  # noqa: N806
    new_limit = 2015
    Flat.objects.filter(
        construction_year__gte=new_limit
    ).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building, revert_fill_new_building)
    ]
