# Generated by Django 2.2.24 on 2022-10-17 18:48

from django.db import migrations

# pylint: disable=unused-argument


def shift_owners(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    owner_model = apps.get_model('property', 'Owner')
    flats = flat_model.objects.all()
    for flat in flats:
        owner_model.objects.update_or_create(
            name=flat.owner,
            pure_phone=flat.owner_pure_phone,
            defaults={
                'name': flat.owner,
                'phonenumber': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone}
        )


def revert_shift_owners(apps, schema_editor):
    owner_model = apps.get_model('property', 'Owner')
    owners = owner_model.objects.all()
    owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221017_2026'),
    ]

    operations = [
        migrations.RunPython(shift_owners, revert_shift_owners)
    ]
