# Generated by Django 2.2.24 on 2022-10-17 18:48

from django.db import migrations

# pylint: disable=unused-argument


def shift_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')  # noqa: N806
    Owner = apps.get_model('property', 'Owner')  # noqa: N806
    flats = Flat.objects.all()
    if not flats.exists():
        return
    for flat in flats.iterator():
        Owner.objects.update_or_create(
            name=flat.owner,
            pure_phone=flat.owner_pure_phone,
            defaults={
                'name': flat.owner,
                'phonenumber': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone}
        )


def revert_shift_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')  # noqa: N806
    owners = Owner.objects.all()
    owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221017_2026'),
    ]

    operations = [
        migrations.RunPython(shift_owners, revert_shift_owners)
    ]
