# Generated by Django 2.2.24 on 2022-10-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_bind_flats_to_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
